export const COLORS = [
  "alpine",
  "azul",
  "aura",
  "aura glow",
  "artic",
  "astral",
  "crush",
  "amber yellow",
  "awesome lilac",
  "awesome lemon",
  "amarillo",
  "awesome graphite",
  "awesome navy",
  "awesome iceblue",
  "black",
  "blanco",
  "blue",
  "blush",
  "blue shadow",
  "bora purple",
  "beige",
  "bronze",
  "burgundy",
  "breathing",
  "carbon",
  "carbon gray",
  "claro",
  "cloud",
  "cloud blue",
  "cloud pink",
  "cobalt violet",
  "coralred",
  "cosmic",
  "cosmic grey",
  "cosmic orange",
  "cosmic white",
  "cosmig",
  "cosmo",
  "cocoa",
  "celestial",
  "crafted black",
  "crema",
  "cream",
  "ceramic",
  "crystal",
  "crush",
  "chrome",
  "cyan",
  "ds mystyc bronze",
  "dark",
  "dark green",
  "deep",
  "deep blue",
  "desert",
  "desert titanium",
  "dorado",
  "emerald dusk",
  "frost",
  "gold",
  "grafito",
  "graphite",
  "graphite gray",
  "green",
  "gris",
  "gray",
  "glacier",
  "glacial",
  "graygreen",
  "frosty",
  "hace",
  "icyblue",
  "indigo",
  "interstellar Grey",
  "jetblack",
  "jadegreen",
  "kinda coral",
  "lake",
  "lavanda",
  "lavender",
  "lemongrass",
  "lima",
  "lime",
  "light",
  "meadow",
  "midnight",
  "midnight black",
  "myctic bronze",
  "mint",
  "moonstone",
  "morning mist",
  "flip moonlit",
  "morado",
  "moonlight",
  "mystic",
  "marbey",
  "naranja",
  "neo beauty",
  "nfc midnight",
  "navy",
  "negro",
  "nebula",
  "oscuro",
  "obsidiana",
  "obsidian",
  "obsidiante",
  "olive",
  "onyx gray",
  "oro",
  "orange",
  "pearl white",
  "pacific",
  "phantom",
  "phantom azul",
  "phantom amber",
  "phantom ambar",
  "phantom awesome",
  "phantom black",
  "phantom blue",
  "phantom cobalt",
  "phantom coral",
  "phantom cream",
  "phantom desert",
  "phantom dorado",
  "phantom frost",
  "phantom gold",
  "phantom gray",
  "phantom gris",
  "phantom green",
  "phantom hielo",
  "phantom icy",
  "phantom jet",
  "phantom lavanda",
  "phantom lemon",
  "phantom lima",
  "phantom mint",
  "phantom morado",
  "phantom naranja",
  "phantom navy",
  "phantom violet",
  "phantom white",
  "product",
  "pink",
  "plateado",
  "porcelain",
  "prism",
  "prism dot",
  "prism green",
  "prism red",
  "prism white",
  "purple",
  "polar",
  "red",
  "rojo",
  "rose",
  "rosa",
  "sierra blue",
  "silver",
  "silverblue",
  "silver shadow",
  "sky blue",
  "space",
  "sorta seafoam",
  "space grey",
  "space black",
  "starlight",
  "startrails",
  "stormy black",
  "starry",
  "twilight",
  "twilight grey",
  "titanio ambar",
  "titanio awesome",
  "titanio blanco",
  "titanio cielo",
  "titanio crema",
  "titanio cobalto",
  "titanio coral",
  "titanio dorado",
  "titanio fantasma",
  "titanio gris",
  "titanio hielo",
  "titanio jet",
  "titanio lavanda",
  "titanio lima",
  "titanio menta",
  "titanio morado",
  "titanio naranja",
  "titanio negro",
  "titanio nube",
  "titanio plateado",
  "titanio prisma",
  "titanio rojo",
  "titanio rosa",
  "titanio sombra",
  "titanio sorta",
  "titanio tormenta",
  "titanio violeta",
  "titanio blanco",
  "titanio amarillo",
  "titanum",
  "titanium",
  "titanium amber",
  "titanium awesome",
  "titanium azul",
  "titanium black",
  "titanium cloud",
  "titanium cobalt",
  "titanium coral",
  "titanium coralred",
  "titanium icy",
  "titanium jet",
  "titanium grey",
  "titanium jetblack",
  "titanium lavender",
"titanium lemon",
"titanium lime",
  "titanium kinda",
  "titanium midnight",
  "titanium mint",
  "titanium orange",
  "titanium phantom",
  "titanium prism",
  "titanium red",
  "titanium shadow",
  "titanium silver",
  "titanium sky",
  "titanium sorta",
  "titanium stormy",
  "titanium violet",
  "titanium violeta",
  "titanium white",
  "titanium yellow",
  "klein",
  "verde",
  "vert citron",
  "violet",
  "violeta",
  "white",
  "yellow"
];